### Setup

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
import seaborn as sns
%matplotlib inline

### 3.1

In [2]:
train = pd.read_csv("train.csv")
train

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,3063,3064,3065,3066,3067,3068,3069,3070,3071,label
0,0,253,251,252,252,252,252,252,251,251,...,142,140,141,141,139,139,139,137,133,17
1,1,252,251,252,252,251,252,252,252,252,...,44,48,89,79,59,55,65,71,77,17
2,2,58,64,70,70,68,66,65,65,68,...,26,30,28,21,26,23,21,21,23,76
3,3,117,119,118,118,117,118,118,118,118,...,70,43,17,33,65,69,69,66,68,68
4,4,60,60,60,61,61,61,61,61,61,...,102,99,95,93,94,98,101,102,101,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,2495,129,128,129,129,129,131,131,133,136,...,103,107,109,105,101,80,68,76,74,76
2496,2496,255,254,255,255,255,255,255,255,255,...,179,170,154,142,166,168,168,165,152,37
2497,2497,203,205,206,206,207,210,212,214,215,...,85,89,86,88,87,83,82,83,81,68
2498,2498,56,66,73,56,88,101,74,51,49,...,163,184,191,140,194,249,244,246,249,12
2499,2499,218,214,221,223,217,205,192,220,251,...,112,96,130,180,184,190,190,175,145,12

### 3.2

In [3]:
from sklearn.svm import SVC
from sklearn import svm
from sklearn.model_selection import cross_validate
X_train = train.drop('label', axis= 1)
Y_train = train['label']
print(X_train)
print(Y_train)

      Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  3062  \
0              0  253  251  252  252  252  252  252  251  251  ...   139
1              1  252  251  252  252  251  252  252  252  252  ...    50
2              2   58   64   70   70   68   66   65   65   68  ...    20
3              3  117  119  118  118  117  118  118  118  118  ...    69
4              4   60   60   60   61   61   61   61   61   61  ...   101
...          ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...
2495        2495  129  128  129  129  129  131  131  133  136  ...   102
2496        2496  255  254  255  255  255  255  255  255  255  ...   184
2497        2497  203  205  206  206  207  210  212  214  215  ...   105
2498        2498   56   66   73   56   88  101   74   51   49  ...   223
2499        2499  218  214  221  223  217  205  192  220  251  ...   110

      3063  3064  3065  3066  3067  3068  3069  3070  3071
0      142   140   141   141   139   139   139   137   133
1       44    48    89    79    59    55    65    71    77
2       26    30    28    21    26    23    21    21    23
3       70    43    17    33    65    69    69    66    68
4      102    99    95    93    94    98   101   102   101
...    ...   ...   ...   ...   ...   ...   ...   ...   ...
2495   103   107   109   105   101    80    68    76    74
2496   179   170   154   142   166   168   168   165   152
2497    85    89    86    88    87    83    82    83    81
2498   163   184   191   140   194   249   244   246   249
2499   112    96   130   180   184   190   190   175   145

[2500 rows x 3073 columns]
0       17
1       17
2       76
3       68
4       76
        ..
2495    76
2496    37
2497    68
2498    12
2499    12
Name: label, Length: 2500, dtype: int64

In [4]:
SVC_List = []

SVC1 = svm.SVC(C=0.5, kernel = 'linear')
SVC1.fit(X_train, Y_train)
SVC_List.append(SVC1)

SVC2 = svm.SVC(C=1, kernel = 'linear')
SVC2.fit(X_train, Y_train)
SVC_List.append(SVC2)

SVC3 = svm.SVC(C=2, kernel = 'linear')
SVC3.fit(X_train, Y_train)
SVC_List.append(SVC3)

SVC4 = svm.SVC(C=0.5, kernel = 'rbf')
SVC4.fit(X_train, Y_train)
SVC_List.append(SVC4)

SVC5 = svm.SVC(C=1, kernel = 'rbf')
SVC5.fit(X_train, Y_train)
SVC_List.append(SVC5)

SVC6 = svm.SVC(C=2, kernel = 'rbf')
SVC6.fit(X_train, Y_train)
SVC_List.append(SVC6)

SVC7 = svm.SVC(C= 0.5 , kernel = 'poly', degree = 2 )
SVC7.fit(X_train, Y_train)
SVC_List.append(SVC7)

SVC8 = svm.SVC(C= 0.5 , kernel = 'poly', degree = 3 )
SVC8.fit(X_train, Y_train)
SVC_List.append(SVC8)

SVC9 = svm.SVC(C= 0.5 , kernel = 'poly', degree = 5 )
SVC9.fit(X_train, Y_train)
SVC_List.append(SVC9)

SVC10 = svm.SVC(C= 1 , kernel = 'poly', degree = 2  )
SVC10.fit(X_train, Y_train)
SVC_List.append(SVC10)

SVC11 = svm.SVC(C= 1, kernel = 'poly', degree = 3 )
SVC11.fit(X_train, Y_train)
SVC_List.append(SVC11)

SVC12 = svm.SVC(C= 1, kernel = 'poly', degree = 5 )
SVC12.fit(X_train, Y_train)
SVC_List.append(SVC12)

SVC13 = svm.SVC(C= 2, kernel = 'poly', degree = 2 )
SVC13.fit(X_train, Y_train)
SVC_List.append(SVC13)

SVC14 = svm.SVC(C= 2, kernel = 'poly', degree = 3 )
SVC14.fit(X_train, Y_train)
SVC_List.append(SVC14)

SVC15 = svm.SVC(C= 2, kernel = 'poly', degree = 5 )
SVC15.fit(X_train, Y_train)
SVC_List.append(SVC15)

In [5]:
for n in SVC_List:
    cross_val = cross_validate(n, X_train, Y_train, cv = 5, scoring = "accuracy")
    average_score = cross_val["test_score"].mean()
    print("Average Accuracy Test Score of", n, "=", average_score)

Average Accuracy Test Score of SVC(C=0.5, kernel='linear') = 0.48200000000000004
Average Accuracy Test Score of SVC(C=1, kernel='linear') = 0.48200000000000004
Average Accuracy Test Score of SVC(C=2, kernel='linear') = 0.48200000000000004
Average Accuracy Test Score of SVC(C=0.5) = 0.5915999999999999
Average Accuracy Test Score of SVC(C=1) = 0.616
Average Accuracy Test Score of SVC(C=2) = 0.6328
Average Accuracy Test Score of SVC(C=0.5, degree=2, kernel='poly') = 0.5928
Average Accuracy Test Score of SVC(C=0.5, kernel='poly') = 0.5756000000000001
Average Accuracy Test Score of SVC(C=0.5, degree=5, kernel='poly') = 0.5316
Average Accuracy Test Score of SVC(C=1, degree=2, kernel='poly') = 0.5944
Average Accuracy Test Score of SVC(C=1, kernel='poly') = 0.5711999999999999
Average Accuracy Test Score of SVC(C=1, degree=5, kernel='poly') = 0.5279999999999999
Average Accuracy Test Score of SVC(C=2, degree=2, kernel='poly') = 0.5812
Average Accuracy Test Score of SVC(C=2, kernel='poly') = 0.564
Average Accuracy Test Score of SVC(C=2, degree=5, kernel='poly') = 0.5267999999999999

### 3.3

In [6]:
#test
test = pd.read_csv("test.csv")
test

X_test = test.drop('label', axis= 1)
Y_test = test['label']
print(X_test)
print(Y_test)

     Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  3062  3063  \
0             0  162  130  162  119  103  193  244  242  246  ...    46    91
1             1   85   93  105  112  143  177  148  135  138  ...    65    49
2             2  158  133  159  183  218  249  255  255  253  ...   130   127
3             3   88   86   85   85   86   86   87   87   87  ...    69   174
4             4  126  126  126  126  130  133  134  135  133  ...    47    68
..          ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...
495         495  191  189  190  186  184  183  182  182  185  ...    56    62
496         496  237  235  235  233  231  228  226  224  222  ...    93    99
497         497   88   89  110  137  136  134  133  131  129  ...   106    96
498         498  255  252  253  253  253  253  253  253  253  ...   245   226
499         499  200  199  199  199  198  199  198  197  196  ...   137   134

     3064  3065  3066  3067  3068  3069  3070  3071
0      79    83   109   125   137   145   151   147
1      41    45    53    64    64    62    61    47
2     122   119   118   118   117   112   109   110
3     153    87    63    60    95   166   168   122
4      60    35    20    32    38    34    36    39
..    ...   ...   ...   ...   ...   ...   ...   ...
495    54    67   100   111    98   101    97    81
496   103   103    98    84    45    16    11    10
497   105   111   116   186   232   233   233   228
498   203   204   220   233   234   229   229   238
499   137   139   143   146   147   149   147   149

[500 rows x 3073 columns]
0      37
1      17
2      37
3      76
4      17
       ..
495    68
496    68
497    76
498    37
499    12
Name: label, Length: 500, dtype: int64

In [7]:
#insert best SVC Model: SV6
SVC_best = SVC(C=2, kernel = 'rbf')
SVC_best.fit(X_train,Y_train) 

Y_prediction = SVC_best.predict(X_test)
print(Y_prediction)

from sklearn.metrics import accuracy_score 
accuracy_score(Y_test, Y_prediction)

[17 76 68 76 17 37 12 12 68 37 12 37 12 76 12 76 76 17 12 68 68 12 12 76
 17 37 68 76 76 68 37 17 76 17 76 37 12 68 68 76 12 76 12 37 68 76 37 12
 37 12 12 76 37 37 12 37 76 17 37 12 37 76 68 12 17 37 12 12 68 17 76 76
 76 37 76 12 68 37 37 12 68 12 17 12 37 37 12 12 76 68 76 76 37 37 17 76
 68 12 76 12 17 12 17 37 76 68 17 17 17 17 68 37 17 17 37 68 17 76 12 76
 17 76 68 37 37 68 17 17 68 17 68 68 37 76 12 76 76 17 76 37 76 37 76 12
 76 37 76 17 76 12 68 76 12 17 17 17 68 12 68 68 17 37 68 68 68 76 68 12
 76 17 76 37 76 76 17 76 37 12 68 76 37 68 76 17 68 76 68 12 76 12 76 17
 37 12 17 37 12 76 68 17 68 12 68 76 68 12 68 37 17 76 76 17 37 12 17 76
 76 68 17 17 37 12 37 68 12 68 17 37 68 17 37 37 76 12 68 68 12 17 68 17
 12 12 17 12 68 76 68 37 68 12 37 37 68 76 12 76 68 12 76 37 68 17 12 17
 68 12 68 12 37 68 68 76 76 37 76 76 68 76 17 37 68 68 76 17 76 76 17 76
 76 17 76 12 76 76 37 12 12 76 17 68 12 68 37 68 12 37 37 12 68 17 12 12
 12 37 17 17 17 76 68 12 17 76 37 12 17 12 12 17 68 76 68 76 37 17 12 17
 12 76 37 68 37 12 37 12 68 37 68 76 17 76 76 12 76 76 76 17 37 68 76 37
 68 37 68 12 68 17 12 68 68 76 12 37 76 17 17 37 37 37 68 12 12 76 76 37
 37 37 76 37 37 37 76 68 37 12 12 68 12 17 12 17 68 12 12 76 12 68 68 12
 37 76 37 37 37 68 76 76 17 37 68 17 12 37 68 68 12 76 37 12 37 37 68 17
 76 17 37 17 68 68 17 12 37 12 17 76 17 76 68 68 37 12 68 68 37 12 68 12
 12 17 37 37 17 37 68 76 17 68 37 68 12 76 68 37 68 17 76 17 37 76 76 37
 12 37 76 12 68 12 37 76 37 76 17 37 37 76 37 68 68 76 17 12]

0.62

### 3.4

Accuracy score is a decent metric for seeing accuracy of model because it is a binary metric, either the prediction is a hit or miss. However, this data set is pixels for "large man-made outdoor things" and large manmade things such as a castle, house, or skyscraper are classified as different objects but are technically under a similar category as a "building". Therefore, more nuance in accuracy scoring could be achieved. For example, the model may predict a castle as a house which isn't necessarily incorrect. But accuracy_score will clasify this prediction as completely incorrect. 

What accuracy score could be used to improve this? Possibly the adjusted_rand_score because it is a clustering scoring method that "computes a similarity measure between two clusterings"